name = "china-apps-navigator"
compatibility_date = "2024-01-19"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build"
cwd = "."

[site]
bucket = ".next"
pages_build_output_dir = ".next"

[env.production]
name = "china-apps-navigator"
routes = ["china-apps-navigator.pages.dev/*"]
